/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/abdyebPjsOi
 */
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { TableCell, TableRow, TableBody, Table } from "@/components/ui/table"

export function Page() {
  return (
    (<div className="max-w-8xl md:mx-20 mx-3  md:py-12 py-5 px-4 sm:px-6 lg:px-8 bg-white">
      <div className="md:grid md:grid-cols-3 ">
        <div className="md:col-span-2 col-span-3 max-w-8xl">
          <h1 className="md:text-4xl text-[26px] font-bold text-black">Al Khalid Tours & Travels</h1>
          <p className="md:text-md text-sm md:w-full w-64 text-gray-500">
            Byculla, Mumbai , Maharashtra, India <span className="text-yellow-600 md:pl-5 pl-1">★ 4.5</span> · 288 reviews
          </p>
          <div className="mt-6 max-w-2xl flex md:flex-row flex-row md:justify-around   items-center font-semibold space-x-2">
            <div className="">
                <Button className="bg-black text-white">15 Days</Button>
            </div>
          <div className="flex md:flex-row  flex-col md:text-lg md:pl-0 pl-4 text-sm md:space-x-4">
            <div className="flex items-center flex-row md:w-auto w-full space-x-2">
              <CalendarIcon className="text-gray-600" />
              <span className="">31 Aug</span>  <span className="px-1">|</span> 
            
              <PlaneTakeoffIcon className="text-gray-600 " />
              <span className="">14 Sep</span>
            </div>

            <div className="md:w-auto ">
                <p className="md:text-lg text-sm md:pl-3">Departure Location: Mumbai</p>
            </div>
          </div>
          </div>

          <div className="md:hidden block pt-10">
        <PriceBox/>
        </div>

          <div className="mt-8">
            <h2 className="md:text-3xl text-xl md:pt-10 pt-8 font-semibold">Package Inclusions</h2>
            <ul className="mt-4 text-lg space-y-2">
              <li className="flex items-center space-x-4">
                <CheckIcon className="text-green-500" />
                <span>Air Fare</span>
              </li>
              <li className="flex items-center space-x-4">
                <TicketIcon className="text-gray-600" />
                <span>Visa with Insurance</span>
              </li>
              <li className="flex items-center space-x-4">
                <HotelIcon className="text-gray-600" />
                <span>Accomodation</span>
              </li>
              <li className="flex items-center space-x-4">
                <BusIcon className="text-gray-600" />
                <span>Round Trip Transfers in Groups</span>
              </li>
              <li className="flex items-center space-x-4">
                <ChurchIcon className="text-gray-600" />
                <span>Ziarat</span>
              </li>
              <li className="flex items-center space-x-4">
                <UtensilsIcon className="text-gray-600" />
                <span>Full Board Meals</span>
              </li>
              <li className="flex items-center space-x-4">
                <ShirtIcon className="text-gray-600" />
                <span>Laundry</span>
              </li>
              <li className="flex items-center space-x-4">
                <BriefcaseIcon className="text-gray-600" />
                <span className=" line-through">TCS</span>
              </li>
              <li className="flex items-center space-x-4">
                <CarTaxiFrontIcon className="text-gray-600" />
                <span className=" line-through">Individual Transfer</span>
              </li>
            </ul>
          </div>
        </div>
        <div className="md:block hidden">
        <PriceBox/>
        </div>
      
      <div className="w-full">
        <Hotels/>
      </div>
      </div>
    </div>)
  );
}

function PriceBox(){
  return(
    (

      <Card className="w-3xl right-10 md:flex flex-col py-5 font-sans ">
      <CardHeader>
        <CardTitle className="tracking-wide">Pricing</CardTitle>
      </CardHeader>
      <CardContent>
        <Table className="mb-2">
          <TableBody>
            <TableRow>
              <TableCell className="font-semibold">2 Share</TableCell>
              <TableCell className="text-right">₹ 1,95,000</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-semibold">3 Share</TableCell>
              <TableCell className="text-right">₹ 1,75,000</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-semibold">4 Share</TableCell>
              <TableCell className="text-right">₹ 1,60,000</TableCell>
            </TableRow>
          </TableBody>
        </Table>
        <p className="md:text-sm text-xs text-gray-500 mt-2">All Prices are Per Person</p>
        <p className="md:text-sm text-xs text-gray-500">* Child without bed - ₹ 45,000, Infant - ₹ 30,000</p>
      </CardContent>
      <CardFooter className="flex justify-center mt-2">
       <button className="bg-black text-white py-3 px-5 rounded-lg font-semibold"> Book Now </button>
      </CardFooter>
    </Card>
    )
  );
}

function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>)
  );
}


function PlaneTakeoffIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 22h20" />
      <path
        d="M6.36 17.4 4 17l-2-4 1.1-.55a2 2 0 0 1 1.8 0l.17.1a2 2 0 0 0 1.8 0L8 12 5 6l.9-.45a2 2 0 0 1 2.09.2l4.02 3a2 2 0 0 0 2.1.2l4.19-2.06a2.41 2.41 0 0 1 1.73-.17L21 7a1.4 1.4 0 0 1 .87 1.99l-.38.76c-.23.46-.6.84-1.07 1.08L7.58 17.2a2 2 0 0 1-1.22.18Z" />
    </svg>)
  );
}


function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>)
  );
}


function TicketIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z" />
      <path d="M13 5v2" />
      <path d="M13 17v2" />
      <path d="M13 11v2" />
    </svg>)
  );
}


function HotelIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M18 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2Z" />
      <path d="m9 16 .348-.24c1.465-1.013 3.84-1.013 5.304 0L15 16" />
      <path d="M8 7h.01" />
      <path d="M16 7h.01" />
      <path d="M12 7h.01" />
      <path d="M12 11h.01" />
      <path d="M16 11h.01" />
      <path d="M8 11h.01" />
      <path d="M10 22v-6.5m4 0V22" />
    </svg>)
  );
}


function BusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 6v6" />
      <path d="M15 6v6" />
      <path d="M2 12h19.6" />
      <path
        d="M18 18h3s.5-1.7.8-2.8c.1-.4.2-.8.2-1.2 0-.4-.1-.8-.2-1.2l-1.4-5C20.1 6.8 19.1 6 18 6H4a2 2 0 0 0-2 2v10h3" />
      <circle cx="7" cy="18" r="2" />
      <path d="M9 18h5" />
      <circle cx="16" cy="18" r="2" />
    </svg>)
  );
}


function ChurchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m18 7 4 2v11a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9l4-2" />
      <path d="M14 22v-4a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v4" />
      <path d="M18 22V5l-6-3-6 3v17" />
      <path d="M12 7v5" />
      <path d="M10 9h4" />
    </svg>)
  );
}


function UtensilsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2" />
      <path d="M7 2v20" />
      <path d="M21 15V2v0a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7" />
    </svg>)
  );
}


function ShirtIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z" />
    </svg>)
  );
}


function BriefcaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>)
  );
}


function CarTaxiFrontIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M10 2h4" />
      <path
        d="m21 8-2 2-1.5-3.7A2 2 0 0 0 15.646 5H8.4a2 2 0 0 0-1.903 1.257L5 10 3 8" />
      <path d="M7 14h.01" />
      <path d="M17 14h.01" />
      <rect width="18" height="8" x="3" y="10" rx="2" />
      <path d="M5 18v2" />
      <path d="M19 18v2" />
    </svg>)
  );
}


function Hotels() {
  return (
    (<div className="max-w-8xl mx-auto my-8 space-y-8">
      <div className="bg-white md:w-[850px]  rounded-lg shadow-lg p-6 ">
        <div className="flex flex-col  md:items-center md:justify-between">
          <h2 className="text-md tracking-tight font-semibold text-center">Hotel in Makkah</h2>
          <h3 className="text-2xl tracking-wide font-bold mt-2 md:mt-0 text-center">Le Meredien Makkah</h3>
        </div>
        <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">
          <img
            alt="Le Meredien Makkah"
            className="rounded-lg"
            
            src="/lemeridien.jpg"
            style={{
             height:"250px",
             aspectRatio: "500/250",
              objectFit: "cover",
            }}
            
           />
          <div className="md:pl-6">
          <iframe className="h-[250px] w-full  "   src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d8682.3064350534!2d39.82332442779449!3d21.418667748598253!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x15c204bc0fcb101d%3A0x272f95a1334c6c6a!2sLe%20M%C3%A9ridien%20Makkah!5e0!3m2!1sen!2sin!4v1709217515548!5m2!1sen!2sin"  allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
          </div>
        </div>
        <div className="flex justify-center items-center space-x-2 mt-6">
          <StarIcon className="text-yellow-400 w-5 h-5" />
          <span className="text-sm font-semibold">5 Star</span>
          <LocateIcon className="text-gray-700 w-5 h-5" />
          <span className="text-sm font-semibold">150 meters</span>
        </div>
      </div>

      <div className="bg-white md:w-[850px] rounded-lg shadow-lg p-6 ">
        <div className="flex flex-col  md:items-center md:justify-between">
          <h2 className="text-md tracking-tight font-semibold text-center">Hotel in Madinah</h2>
          <h3 className="text-2xl tracking-wide font-bold mt-2 md:mt-0 text-center">Royal Al Nokbah</h3>
        </div>
        <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">
          <img
            alt="Royal Al Nokbah"
            className="rounded-lg"
            
            src="/nokbah.jpg"
            style={{
             height:"250px",
              objectFit: "cover",
            }}
            width="500" 
           />
          <div className="md:pl-6 ">
          <iframe className="h-[250px] w-full "   src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d8682.3064350534!2d39.82332442779449!3d21.418667748598253!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x15c204bc0fcb101d%3A0x272f95a1334c6c6a!2sLe%20M%C3%A9ridien%20Makkah!5e0!3m2!1sen!2sin!4v1709217515548!5m2!1sen!2sin"  allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
          </div>
        </div>
        <div className="flex justify-center items-center space-x-2 mt-6">
          <StarIcon className="text-yellow-400 w-5 h-5" />
          <span className="text-sm font-semibold">5 Star</span>
          <LocateIcon className="text-gray-700 w-5 h-5" />
          <span className="text-sm font-semibold">150 meters</span>
        </div>
      </div>
    </div>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}


function LocateIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>)
  );
}
