/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/539fNPeFX41
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"

export function sel() {
  return (
    (<div
      className="mx-auto mt-10 flex w-full max-w-4xl items-center justify-between rounded-full bg-[#75E6DA] p-4">
      <Select className="flex-1">
        <SelectTrigger id="issue-type">
          <SelectValue placeholder="Your Presenting issues" />
        </SelectTrigger>
        <SelectContent position="popper">
          <SelectItem value="issue1">Issue 1</SelectItem>
          <SelectItem value="issue2">Issue 2</SelectItem>
          <SelectItem value="issue3">Issue 3</SelectItem>
        </SelectContent>
      </Select>
      <ChevronDownIcon className="mx-2 text-black" />
      <Select className="flex-1">
        <SelectTrigger id="language">
          <SelectValue placeholder="Languages" />
        </SelectTrigger>
        <SelectContent position="popper">
          <SelectItem value="english">English</SelectItem>
          <SelectItem value="spanish">Spanish</SelectItem>
          <SelectItem value="french">French</SelectItem>
        </SelectContent>
      </Select>
      <ChevronDownIcon className="mx-2 text-black" />
      <Input className="flex-1" placeholder="Search" />
    </div>)
  );
}


function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}
